"""Add attendees table

Revision ID: bdad6b3a1d3b
Revises: cffca76e4ae7
Create Date: 2025-08-24 22:06:39.843771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdad6b3a1d3b'
down_revision = 'cffca76e4ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_night_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_night_id'], ['game_nights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_night_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendees')
    # ### end Alembic commands ###
